Repository redhat-developer/consoledot-e2e, pull requests merged in 2023-01, with the labels that each got.

#73 Add TEST_ADMIN creds to readme
  Readme.md
Labels: do-not-merge/work-in-progress

#77 Create gh release only if results file exists
  .github/workflows/playwright.yml
Labels: enhancement, skip-jenkins

#81 NEW: test edit Topic properties
  tests/kas_with_instance.spec.ts
Labels: enhancement

#84 NEW: Test GCP Instance Creation
  lib/cloudproviders.ts
  lib/kafka.ts
  tests/kas.spec.ts
Labels: enhancement

#83 Add status badge for main plawright run
  Readme.md
Labels: skip-jenkins

#89 Ability to enable slow mode in playwright tests
  Readme.md
  playwright.config.ts
Labels: enhancement

#90 UPDATE: made SA instance name dynamic to prevent collisions
  tests/rhosak/kas_messaging.spec.ts
Labels: enhancement
