Repository redhat-developer/consoledot-e2e, pull requests merged in 2023-02, with the labels that each got.

#86 MGDSTRM-10375 NEW: Migration of remaining Tests on test_4kafka
  tests/rhosak/kas_with_instance.spec.ts
Labels: enhancement

#94 Hotfix/aftereach sa cleanup
  lib/sa.ts
  tests/console-dot/sa.spec.ts
  tests/rhosak/kas_messaging.spec.ts
Labels: bug

#91 UPDATE: changed flaky locators
  tests/rhosak/kas_with_instance.spec.ts
Labels: enhancement

#97 FIX: changed flaky search locator for messages
  tests/rhosak/kas_messaging.spec.ts
Labels: bug

#98 UPDATE: skip only filterBy Timestamp test case
  tests/rhosak/kas_messaging.spec.ts
Labels: bug

#99 NEW: Test for custom Topic properties different than default
  lib/topic.ts
  tests/rhosak/kas_messaging.spec.ts
  tests/rhosak/kas_with_instance.spec.ts
Labels: enhancement

#100 NEW: add mechanism to skip test in case of Out of Quota Error
  lib/kafka.ts
Labels: enhancement, do-not-merge/work-in-progress

#115 Allow to enable err logging
  .gitignore
  Readme.md
  lib/auth.ts
  lib/config.ts
  lib/console_err_listener.ts
  playwright.config.ts
Labels: enhancement

#116 Check results.xml existence always in gh acrion pipeline
  .github/workflows/playwright.yml
Labels: skip-jenkins

#117 Make release with test reuslts only when pipeline is not aborted
  .github/workflows/playwright.yml
Labels: skip-jenkins
